# Generated by Django 3.0.8 on 2022-08-26 14:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('test', 'Тестовый'), ('prod', 'Боевой')], default='test', max_length=7, verbose_name='Режим')),
                ('token', models.CharField(blank=True, max_length=63, null=True, verbose_name='Токен')),
                ('pickup_type', models.PositiveIntegerField(choices=[(1, 'Забор груза от двери'), (2, 'Самостоятельная доставка до ПВ')], default=2, verbose_name='Тип приема груза')),
                ('region', models.CharField(blank=True, help_text='Например: "Московская область"', max_length=127, null=True, verbose_name='Область, республика или край')),
                ('city', models.CharField(blank=True, help_text='Например: "Москва"', max_length=100, null=True, verbose_name='Город или населенный пункт')),
                ('city_guid', models.CharField(blank=True, help_text='https://fias.nalog.ru/Search', max_length=63, null=True, verbose_name='ID города в базе ФИАС')),
                ('include_fee', models.BooleanField(default=False, help_text='Суммировать к итоговой стоимости все сборы СД(страховка и комиссия за НП)', verbose_name='Добавлять все сборы СД')),
                ('timeout', models.PositiveIntegerField(default=2, help_text='Время ожидания ответа от провайдера, результаты по провайдерам которые не успели в указанное время выдаваться не будут.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='Время ожидания ответа СД (секунд)')),
            ],
            options={
                'verbose_name': 'Настройки',
                'verbose_name_plural': 'Настройки',
            },
        ),
        migrations.CreateModel(
            name='OrderShipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='apiship', to='shop.Order')),
            ],
            options={
                'verbose_name': 'Доставка',
                'verbose_name_plural': 'Доставка',
            },
        ),
    ]
