# Generated by Django 3.0.8 on 2022-08-26 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HTMLTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html_tag', models.CharField(help_text='Без <>', max_length=200, verbose_name='html тег')),
                ('attrs', models.CharField(blank=True, default='', max_length=1000, verbose_name='Атрибуты тега')),
                ('timeoutTime', models.PositiveIntegerField(default=0, verbose_name='Время выгрузки тега')),
            ],
        ),
    ]
