# Generated by Django 3.0.8 on 2022-08-26 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_htmltag'),
    ]

    operations = [
        migrations.CreateModel(
            name='HTMLGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('header', 'Шапка'), ('footer', 'Подвал')], default='header', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='htmltag',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='configuration.HTMLGroup'),
        ),
    ]
