# Generated by Django 3.0.8 on 2022-08-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0004_auto_20220826_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='htmltag',
            name='innerHTML',
            field=models.CharField(blank=True, default='', max_length=2500, verbose_name='Внутренний html контент'),
        ),
    ]
