# Generated by Django 3.0.8 on 2022-08-26 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0005_htmltag_innerhtml'),
    ]

    operations = [
        migrations.AlterField(
            model_name='htmltag',
            name='innerHTML',
            field=models.TextField(blank=True, default='', max_length=2500, verbose_name='Внутренний контент'),
        ),
    ]
