# Generated by Django 3.0.8 on 2022-08-26 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0015_auto_20220621_1513'),
        ('configuration', '0006_auto_20220826_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='htmlgroup',
            name='domain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='domains.Domain'),
        ),
        migrations.AddField(
            model_name='htmlgroup',
            name='nameGroup',
            field=models.CharField(default='', max_length=200, verbose_name='Название группы'),
        ),
    ]
