# Generated by Django 3.0.8 on 2022-08-26 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0015_auto_20220621_1513'),
        ('configuration', '0007_auto_20220826_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='htmlgroup',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domains.Domain'),
        ),
    ]
