# Generated by Django 3.0.8 on 2022-08-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0009_auto_20220826_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='htmltag',
            name='bottomTagContent',
            field=models.TextField(blank=True, default='Нижний контент элемента', max_length=2500),
        ),
        migrations.AddField(
            model_name='htmltag',
            name='topTagContent',
            field=models.TextField(blank=True, default='Верхний контент элемента', max_length=2500),
        ),
    ]
