# Generated by Django 3.0.8 on 2022-08-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0011_auto_20220826_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='htmltag',
            name='attrs',
        ),
        migrations.RemoveField(
            model_name='htmltag',
            name='bottomTagContent',
        ),
        migrations.RemoveField(
            model_name='htmltag',
            name='html_tag',
        ),
        migrations.RemoveField(
            model_name='htmltag',
            name='topTagContent',
        ),
        migrations.AlterField(
            model_name='htmltag',
            name='innerHTML',
            field=models.TextField(blank=True, default='', max_length=2500, verbose_name='Контент'),
        ),
    ]
