# Generated by Django 3.0.8 on 2022-08-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0013_auto_20220826_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='htmltag',
            name='timeoutTime',
            field=models.PositiveIntegerField(default=0, help_text='Работает только для JS', verbose_name='Время исполнения контента'),
        ),
    ]
