# Generated by Django 3.0.8 on 2022-08-26 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0014_auto_20220826_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='htmltag',
            name='type',
            field=models.CharField(choices=[('js', 'JavaScript'), ('html', 'HTML элементы')], default='html', max_length=200, verbose_name='Элемент'),
        ),
    ]
