# Generated by Django 3.0.8 on 2022-08-29 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0015_htmltag_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='htmltag',
            name='attributes',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Атрибуты элемента'),
        ),
        migrations.AddField(
            model_name='htmltag',
            name='tag',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Тег элемента'),
        ),
    ]
