# Generated by Django 3.0.8 on 2021-04-12 13:54

import apps.domains.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('meta_title', models.CharField(blank=True, default='', max_length=255, verbose_name='SEO заголовок')),
                ('meta_description', models.TextField(blank=True, default='', verbose_name='Meta Description')),
                ('meta_keywords', models.TextField(blank=True, default='', verbose_name='Meta Keywords')),
                ('domain', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, validators=[apps.domains.models._simple_domain_name_validator], verbose_name='Имя домена')),
                ('name', models.CharField(max_length=50, verbose_name='Отображаемое имя')),
                ('name_loct', models.CharField(help_text='Пример: "Москве"', max_length=50, verbose_name='Отображаемое имя в предложном падеже')),
                ('address', models.CharField(blank=True, default='', max_length=255, verbose_name='Адрес')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, default='', max_length=31, verbose_name='Номер телефона')),
                ('extra_phones', models.CharField(blank=True, default='', help_text='Введите номера через запятую', max_length=255, verbose_name='Дополнительные номера телефонов')),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Координата X на карте')),
                ('lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Координата Y на карте')),
                ('robots_txt', models.TextField(blank=True, default='', verbose_name='robots.txt')),
                ('header_extra', models.TextField(blank=True, default='', verbose_name='Вывод в head')),
                ('footer_extra', models.TextField(blank=True, default='', verbose_name='Скрипты под footer')),
            ],
            options={
                'verbose_name': 'домен',
                'verbose_name_plural': 'домены',
                'ordering': ['domain'],
            },
            managers=[
                ('objects', apps.domains.models.DomainManager()),
            ],
        ),
    ]
