# Generated by Django 3.0.8 on 2021-06-02 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0004_auto_20210528_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='meta_description',
            field=models.TextField(blank=True, default='', help_text='\n                                        ||object|| - Заголовок объекта\n                                        ||site|| - Название сайта\n                                        ||city|| - Название города текущего поддомена\n                                        ||city1|| - Название города текущего поддомена в предложном падеже\n                                        ||price|| - Цена товара\n                                        ', verbose_name='Meta Description'),
        ),
    ]
