# Generated by Django 3.0.8 on 2022-03-14 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0011_auto_20220222_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='meta_product_meta_description',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='meta_product_title',
        ),
    ]
