# Generated by Django 3.0.8 on 2022-03-31 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0012_auto_20220314_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='name_dat',
            field=models.CharField(default='ters', help_text='Пример: Санкт-Петербургу', max_length=50, verbose_name='Отображаемое имя в дательном падеже'),
            preserve_default=False,
        ),
    ]
