# Generated by Django 3.0.8 on 2022-08-26 14:05

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KomtetSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_id', models.CharField(max_length=31, verbose_name='Идентификатор магазина')),
                ('secret_key', models.CharField(max_length=31, verbose_name='Секретный ключ')),
                ('queue_id', models.CharField(max_length=31, verbose_name='Идентификатор очереди')),
                ('cashier', models.CharField(blank=True, max_length=31, null=True, verbose_name='ФИО кассира')),
                ('cashier_inn', models.CharField(blank=True, max_length=31, null=True, verbose_name='ИНН кассира')),
                ('tax_system', models.PositiveIntegerField(choices=[(0, 'Общая'), (1, 'Упрощённая, доход'), (2, 'Упрощённая, доход - расход'), (3, 'Единый налог на вменённый доход'), (4, 'Единый сельскохозяйственный налог'), (5, 'Патентная система налогообложения')], default=0, verbose_name='Система налогообложения')),
                ('vat_rate', models.CharField(choices=[('no', 'Без НДС'), ('0', 'НДС по ставке 0%'), ('10', 'НДС по ставке 10%'), ('20', 'НДС по ставке 20%'), ('110', 'НДС по расчетной ставке 10/110'), ('120', 'НДС по расчётной ставке 20/120')], default='no', max_length=7, verbose_name='Налоговая ставка')),
                ('print_check', models.BooleanField(default=True, verbose_name='Печатать чек')),
            ],
            options={
                'verbose_name': 'Настройки комтет-кассы',
                'verbose_name_plural': 'Настройки комтет-кассы',
            },
        ),
        migrations.CreateModel(
            name='KomtetRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(blank=True, default='', max_length=63, verbose_name='Ид задачи')),
                ('response', django.contrib.postgres.fields.jsonb.JSONField(blank=True, verbose_name='Ответ кассы')),
                ('status', models.PositiveIntegerField(choices=[(0, 'Не обработан'), (1, 'Успешно'), (2, 'Ошибка')], default=0, verbose_name='Статус')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='komtet', to='shop.Order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Запрос к кассе',
                'verbose_name_plural': 'Запрос к кассе',
            },
        ),
    ]
