# Generated by Django 3.0.8 on 2022-08-26 14:05

import apps.sber_acquiring.models
import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.BooleanField(default=False, verbose_name='Заказ создан успешно')),
                ('bank_id', models.CharField(blank=True, default='', max_length=63, verbose_name='Ид заказа в системе банка')),
                ('bank_url', models.CharField(blank=True, default='', max_length=255, verbose_name='Ссылка на оплату')),
                ('card_number', models.IntegerField(blank=True, max_length=4, null=True, verbose_name='Последние 4 цифры номера карты')),
                ('expiration_date', models.DateTimeField(default=apps.sber_acquiring.models.calc_expiration_date, editable=False, verbose_name='Окончание жизни заказа в банке')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('order', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_data', to='shop.Order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Заказ в банке',
                'verbose_name_plural': 'Заказы в банке',
            },
        ),
        migrations.CreateModel(
            name='SberSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('test', 'Тестовый'), ('prod', 'Боевой')], default='test', max_length=7, verbose_name='Режим')),
                ('session_lifetime', models.PositiveIntegerField(default=1200, validators=[django.core.validators.MinValueValidator(300)], verbose_name='Время жизни заказа в секундах')),
                ('tax_system', models.PositiveIntegerField(choices=[(0, 'Общая'), (1, 'Упрощённая, доход'), (2, 'Упрощённая, доход - расход'), (3, 'Единый налог на вменённый доход'), (4, 'Единый сельскохозяйственный налог'), (5, 'Патентная система налогообложения')], default=0, verbose_name='Система налогообложения')),
                ('vat_rate', models.PositiveIntegerField(choices=[(0, 'Без НДС'), (1, 'НДС по ставке 0%'), (2, 'НДС по ставке 10%'), (6, 'НДС по ставке 20%'), (4, 'НДС по расчетной ставке 10/110'), (7, 'НДС по расчётной ставке 20/120')], default=0, verbose_name='Налоговая ставка')),
                ('username', models.CharField(blank=True, max_length=63, null=True, verbose_name='Имя пользователя')),
                ('password', models.CharField(blank=True, max_length=63, null=True, verbose_name='Пароль')),
                ('token', models.CharField(blank=True, max_length=63, null=True, verbose_name='Токен')),
            ],
            options={
                'verbose_name': 'Настройки эквайринга',
                'verbose_name_plural': 'Настройки эквайринга',
            },
        ),
        migrations.CreateModel(
            name='BankResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Ответ сервера')),
                ('bank_order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='sber_acquiring.BankOrder')),
            ],
        ),
    ]
