# Generated by Django 3.0.8 on 2022-08-29 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_order_send'),
        ('sber_acquiring', '0004_bankorder_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankorder',
            name='order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_data', to='shop.Order', verbose_name='Заказ'),
        ),
    ]
