# Generated by Django 3.0.8 on 2022-08-26 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0001_initial'),
        ('catalog', '__first__'),
        ('domains', '0015_auto_20220621_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=63, verbose_name='Заголовок')),
                ('url', models.CharField(blank=True, default='', max_length=127, verbose_name='Ссылка')),
                ('sort', models.PositiveIntegerField(default=0, verbose_name='Сортировка')),
                ('location', models.CharField(choices=[('head', 'Шапка'), ('foot', 'Подвал'), ('side', 'Сайдбар'), ('catalog', 'Каталог')], max_length=10, verbose_name='Расположение')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Catalog', verbose_name='Категория')),
                ('domain', models.ManyToManyField(to='domains.Domain', verbose_name='Домен')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.BasePage', verbose_name='Страница')),
            ],
            options={
                'verbose_name': 'Элемент меню',
                'verbose_name_plural': 'Меню сайта',
                'ordering': ('sort',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MenuSubItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=63, verbose_name='Заголовок')),
                ('url', models.CharField(blank=True, default='', max_length=127, verbose_name='Ссылка')),
                ('sort', models.PositiveIntegerField(default=0, verbose_name='Сортировка')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Catalog', verbose_name='Категория')),
                ('domain', models.ManyToManyField(to='domains.Domain', verbose_name='Домен')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.BasePage', verbose_name='Страница')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subitems', to='nav.MenuItem', verbose_name='Родительский пункт')),
            ],
            options={
                'verbose_name': 'Подпункт меню',
                'verbose_name_plural': 'Подпункты меню',
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='CatalogMenuItem',
            fields=[
            ],
            options={
                'verbose_name': 'Элемент каталог',
                'verbose_name_plural': 'Каталог',
                'ordering': ('sort',),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('nav.menuitem',),
        ),
        migrations.CreateModel(
            name='FooterMenuItem',
            fields=[
            ],
            options={
                'verbose_name': 'Элемент подвала',
                'verbose_name_plural': 'Подвал сайта',
                'ordering': ('sort',),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('nav.menuitem',),
        ),
        migrations.CreateModel(
            name='HeaderMenuItem',
            fields=[
            ],
            options={
                'verbose_name': 'Элемент шапки',
                'verbose_name_plural': 'Шапка сайта',
                'ordering': ('sort',),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('nav.menuitem',),
        ),
        migrations.CreateModel(
            name='SidebarMenuItem',
            fields=[
            ],
            options={
                'verbose_name': 'Элемент сайдбара',
                'verbose_name_plural': 'Сайдбар',
                'ordering': ('sort',),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('nav.menuitem',),
        ),
    ]
