# Generated by Django 3.0.8 on 2022-08-26 14:05

import apps.commons.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webp_image', models.TextField(blank=True, null=True, verbose_name='Полный путь до webp')),
                ('webp_hash_image', models.TextField(blank=True, null=True, verbose_name='Хэш для webp')),
                ('webp_image_s', models.TextField(blank=True, null=True, verbose_name='Полный путь до webp_small')),
                ('webp_hash_image_s', models.TextField(blank=True, null=True, verbose_name='Хэш для webp_small')),
                ('webp_image_m', models.TextField(blank=True, null=True, verbose_name='Полный путь до webp_medium')),
                ('webp_hash_image_m', models.TextField(blank=True, null=True, verbose_name='Хэш для webp_medium')),
                ('webp_image_l', models.TextField(blank=True, null=True, verbose_name='Полный путь до webp_large')),
                ('webp_hash_image_l', models.TextField(blank=True, null=True, verbose_name='Хэш для webp_large')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.commons.models.image_directory_path, verbose_name='Изображение')),
                ('image_md5', models.CharField(blank=True, default='', help_text='Заполняется автоматически', max_length=63, verbose_name='Хэш изображения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
                ('author', models.CharField(max_length=125, verbose_name='Автор')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('sort', models.PositiveSmallIntegerField(default=0, verbose_name='Сортировка')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalog.Product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['sort', '-date_created'],
            },
        ),
    ]
