# Generated by Django 3.0.8 on 2021-12-02 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_auto_20210430_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipients', models.TextField(verbose_name='Получатели')),
                ('subject', models.CharField(max_length=255, verbose_name='Тема сообщения')),
                ('message', models.TextField(verbose_name='Текст сообщения')),
            ],
        ),
    ]
