# Generated by Django 3.0.8 on 2021-12-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='emails',
            name='from_mail',
            field=models.CharField(default=1, max_length=255, verbose_name='Отправитель'),
            preserve_default=False,
        ),
    ]
