# Generated by Django 3.0.8 on 2021-12-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_emails_from_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='emails',
            name='text',
            field=models.TextField(default=1, verbose_name='Текст сообщения'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emails',
            name='message',
            field=models.TextField(verbose_name='html сообщения'),
        ),
    ]
