# Generated by Django 3.0.8 on 2022-08-26 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompareItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compare_items', to='catalog.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compare_products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'элемент товаров для сравнения',
                'verbose_name_plural': 'Элементы товаров для сравнения',
            },
        ),
    ]
