# Generated by Django 3.0.8 on 2022-08-26 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('domains', '0015_auto_20220621_1513'),
        ('feedback', '0008_auto_20220324_1943'),
        ('catalog', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_1c', models.UUIDField(blank=True, help_text='Заполняется автоматически', null=True, unique=True, verbose_name='Идентификатор 1С')),
                ('is_footer', models.BooleanField(default=False, verbose_name='Показывать в футере')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
                ('title', models.CharField(max_length=127, verbose_name='Название')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('phone', models.TextField(blank=True, default='', verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('working_hours', models.TextField(blank=True, default='', verbose_name='Часы работы')),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Координата X на карте')),
                ('lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Координата Y на карте')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('sort', models.PositiveIntegerField(default=0, verbose_name='Сортировка')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='domains.Domain')),
            ],
            options={
                'verbose_name': 'Магазин (склад)',
                'verbose_name_plural': 'Магазины (склады)',
                'ordering': ('sort',),
            },
        ),
        migrations.CreateModel(
            name='StoreProductQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantity_stores', to='catalog.Product', verbose_name='Товар')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantity_products', to='stores.Store', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Количество на складе',
                'verbose_name_plural': 'Количество на складе',
            },
        ),
        migrations.AddField(
            model_name='store',
            name='products',
            field=models.ManyToManyField(through='stores.StoreProductQuantity', to='catalog.Product', verbose_name='Товары'),
        ),
        migrations.AddField(
            model_name='store',
            name='recipients',
            field=models.ManyToManyField(blank=True, to='feedback.Recipient', verbose_name='Получатели'),
        ),
    ]
